import {
  BsSuitDiamond,
  BsSuitSpade,
  BsSuitHeart,
  BsSuitClub,
} from "react-icons/bs";

const CardsData = [
  {
    title: "heart1",
    value: "1",
    color: "red",
    icon: <BsSuitHeart />,
  },
  {
    title: "heart2",
    value: "2",
    color: "red",
    icon: <BsSuitHeart />,
  },
  {
    title: "heart3",
    value: "3",
    color: "red",
    icon: <BsSuitHeart />,
  },
  {
    title: "heart4",
    value: "4",
    color: "red",
    icon: <BsSuitHeart />,
  },
  {
    title: "heart5",
    value: "5",
    color: "red",
    icon: <BsSuitHeart />,
  },
  {
    title: "heart6",
    value: "6",
    color: "red",
    icon: <BsSuitHeart />,
  },
  {
    title: "heart7",
    value: "7",
    color: "red",
    icon: <BsSuitHeart />,
  },
  {
    title: "heart8",
    value: "8",
    color: "red",
    icon: <BsSuitHeart />,
  },
  {
    title: "heart9",
    value: "9",
    color: "red",
    icon: <BsSuitHeart />,
  },
  {
    title: "heart10",
    value: "10",
    color: "red",
    icon: <BsSuitHeart />,
  },
  {
    title: "heart11",
    value: "J",
    color: "red",
    icon: <BsSuitHeart />,
  },
  {
    title: "heart12",
    value: "Q",
    color: "red",
    icon: <BsSuitHeart />,
  },
  {
    title: "heart13",
    value: "K",
    color: "red",
    icon: <BsSuitHeart />,
  },
  {
    title: "spades1",
    value: "1",
    color: "#45b1fa",
    icon: <BsSuitSpade />,
  },
  {
    title: "spades2",
    value: "2",
    color: "#45b1fa",
    icon: <BsSuitSpade />,
  },
  {
    title: "spades3",
    value: "3",
    color: "#45b1fa",
    icon: <BsSuitSpade />,
  },
  {
    title: "spades4",
    value: "4",
    color: "#45b1fa",
    icon: <BsSuitSpade />,
  },
  {
    title: "spades5",
    value: "5",
    color: "#45b1fa",
    icon: <BsSuitSpade />,
  },
  {
    title: "spades6",
    value: "6",
    color: "#45b1fa",
    icon: <BsSuitSpade />,
  },
  {
    title: "spades7",
    value: "7",
    color: "#45b1fa",
    icon: <BsSuitSpade />,
  },
  {
    title: "spades8",
    value: "8",
    color: "#45b1fa",
    icon: <BsSuitSpade />,
  },
  {
    title: "spades9",
    value: "9",
    color: "#45b1fa",
    icon: <BsSuitSpade />,
  },
  {
    title: "spades10",
    value: "10",
    color: "#45b1fa",
    icon: <BsSuitSpade />,
  },
  {
    title: "spades11",
    value: "J",
    color: "#45b1fa",
    icon: <BsSuitSpade />,
  },
  {
    title: "spades12",
    value: "Q",
    color: "#45b1fa",
    icon: <BsSuitSpade />,
  },
  {
    title: "spades13",
    value: "K",
    color: "#45b1fa",
    icon: <BsSuitSpade />,
  },
  {
    title: "diamond1",
    value: "1",
    color: "red",
    icon: <BsSuitDiamond />,
  },
  {
    title: "diamond2",
    value: "2",
    color: "red",
    icon: <BsSuitDiamond />,
  },
  {
    title: "diamond3",
    value: "3",
    color: "red",
    icon: <BsSuitDiamond />,
  },
  {
    title: "diamond4",
    value: "4",
    color: "red",
    icon: <BsSuitDiamond />,
  },
  {
    title: "diamond5",
    value: "5",
    color: "red",
    icon: <BsSuitDiamond />,
  },
  {
    title: "diamond6",
    value: "6",
    color: "red",
    icon: <BsSuitDiamond />,
  },
  {
    title: "diamond7",
    value: "7",
    color: "red",
    icon: <BsSuitDiamond />,
  },
  {
    title: "diamond8",
    value: "8",
    color: "red",
    icon: <BsSuitDiamond />,
  },
  {
    title: "diamond9",
    value: "9",
    color: "red",
    icon: <BsSuitDiamond />,
  },
  {
    title: "diamond10",
    value: "10",
    color: "red",
    icon: <BsSuitDiamond />,
  },
  {
    title: "diamond11",
    value: "J",
    color: "red",
    icon: <BsSuitDiamond />,
  },
  {
    title: "diamond12",
    value: "Q",
    color: "red",
    icon: <BsSuitDiamond />,
  },
  {
    title: "diamond13",
    value: "K",
    color: "red",
    icon: <BsSuitDiamond />,
  },
  {
    title: "club1",
    value: "1",
    color: "#45b1fa",
    icon: <BsSuitClub />,
  },
  {
    title: "club2",
    value: "2",
    color: "#45b1fa",
    icon: <BsSuitClub />,
  },
  {
    title: "club3",
    value: "3",
    color: "#45b1fa",
    icon: <BsSuitClub />,
  },
  {
    title: "club4",
    value: "4",
    color: "#45b1fa",
    icon: <BsSuitClub />,
  },
  {
    title: "club5",
    value: "5",
    color: "#45b1fa",
    icon: <BsSuitClub />,
  },
  {
    title: "club6",
    value: "6",
    color: "#45b1fa",
    icon: <BsSuitClub />,
  },
  {
    title: "club7",
    value: "7",
    color: "#45b1fa",
    icon: <BsSuitClub />,
  },
  {
    title: "club8",
    value: "8",
    color: "#45b1fa",
    icon: <BsSuitClub />,
  },
  {
    title: "club9",
    value: "9",
    color: "#45b1fa",
    icon: <BsSuitClub />,
  },
  {
    title: "club10",
    value: "10",
    color: "#45b1fa",
    icon: <BsSuitClub />,
  },
  {
    title: "club11",
    value: "J",
    color: "#45b1fa",
    icon: <BsSuitClub />,
  },
  {
    title: "club12",
    value: "Q",
    color: "#45b1fa",
    icon: <BsSuitClub />,
  },
  {
    title: "club13",
    value: "K",
    color: "#45b1fa",
    icon: <BsSuitClub />,
  },
];

export default CardsData;
